repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: Cargo fmt
        description: Run cargo fmt on files included in the commit. rustfmt should be installed before-hand.
        entry: cargo fmt --all --
        pass_filenames: true
        types: [file, rust]
        language: system

      - id: cargo-clippy
        name: Cargo clippy
        description: Run cargo clippy on files included in the commit. clippy should be installed before-hand.
        entry: cargo clippy -- -Dwarnings
        pass_filenames: false
        types: [file, rust]
        language: system
