[package]
name = "spotify_request"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.15", features = ["json"] }
async-std = "1.13.1"
tokio = { version = "1.44.1", features = ["rt", "rt-multi-thread", "macros"] }
serde_json = "1.0.140"
